spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-name: eshare-es
      cluster-nodes: 192.168.1.220:9300,192.168.1.221:9300,192.168.1.222:9300
      local: true
      repositories:
        enabled: true
